apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  selector: 
    app: helloworld-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-app
spec:
  selector:
    matchLabels:
      app: helloworld-app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: helloworld-app
    spec:
      containers:
      - name: helloworld-app
        image: helloworld:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000